DROP DATABASE IF EXISTS conv;
DROP USER 'ADMIN'@'localhost';

CREATE DATABASE `conv` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
use `conv`;


CREATE TABLE IF NOT EXISTS `T_USER` 
(
	ID_USER INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	ID varchar(255) NOT NULL,
	MDP varchar(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS `T_COMMENTAIRE` 
(
    ID_USER1 INT NOT NULL,
	ID_USER2 INT NOT NULL,
	TEXTE varchar(1000),
	ENVOI BOOL  DEFAULT FALSE ,
	constraint PK_T_COMMENTAIRE primary key (ID_USER1, ID_USER2),
	constraint FK_COMMENTAIRE_USER1 foreign key(ID_USER1) references T_USER (ID_USER),
	constraint FK_COMMENTAIRE_USER2 foreign key(ID_USER2) references T_USER (ID_USER)
)

ENGINE=InnoDB DEFAULT CHARSET=utf8 ;
