CREATE USER 'y'@'localhost' IDENTIFIED BY 'y';
GRANT USAGE ON * . * TO 'y'@'localhost' IDENTIFIED BY 'SJzEeqLb2HHeNYVV' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
GRANT ALL PRIVILEGES ON `db_cours_mvc` . * TO 'y'@'localhost';